apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-et-demonstrators.fullname" . }}
  labels:
    {{- include "product-et-demonstrators.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "product-et-demonstrators.selectorLabels" . | nindent 4 }}
