apiVersion: v2
name: product-et-demonstrators
description: A Helm chart of Emerging Tech demonstrators for K8s Catena-X. 


# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# Chart version
version: 0.1.1

# Application version
appVersion: "1.0.0"
